[package]
name = "mqtt_client_rs"
version = "0.1.0"
authors = ["Muhammad Hassan <muhammad.hassan@hyperdatacomputing.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rumqttc="*"
# Tokio 1.0 introduced breaking changes for rumqttc
tokio="0.3.6"
bytes="*"
const_format = "*"
serde_json = "*"
chrono = "*"
